### ISSUE TITLE
Pip install fails

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/olinda#1]
Running setup.py install for lap ... error
  error: subprocess-exited-with-error
When installing olinda using pip, it fails with the following message:  
 
```
 × Running setup.py install for lap did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      Partial import of lap during the build process.
      Traceback (most recent call last):
        File "/tmp/pip-install-_sku92w2/lap_616b1965e4864fae9beb9edcd33fcb24/setup.py", line 127, in get_numpy_status
          import numpy
      ModuleNotFoundError: No module named 'numpy'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-_sku92w2/lap_616b1965e4864fae9beb9edcd33fcb24/setup.py", line 236, in <module>
          setup_package()
        File "/tmp/pip-install-_sku92w2/lap_616b1965e4864fae9beb9edcd33fcb24/setup.py", line 220, in setup_package
          raise ImportError('lap requires numpy, '
      ImportError: lap requires numpy, please "pip install numpy".
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lap

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

```

**Comment by GemmaTuron** [comment]
I have added numpy: 
https://github.com/ersilia-os/olinda/commit/e3c60f1b3fae8428bf61c1b3bdf15b33a35df5df

**Comment by JHlozek** [comment]
@GemmaTuron, the numpy change above fixed the original issue.

However, I needed to restrict tensorflow to version = "^2.9, <2.16.0" to be able to import Olinda once it installed.

In addition, the following two changes are necessary to be able to run current Ersilia models:
- the ersilia version needs updating to "^0.1.31"
- this creates a conflict over pandas, which I can resolve by reducing the version to v1.3.5

I am working through troubleshooting issues further in the Olinda pipeline, but I will post that progress here: #3

**Comment by GemmaTuron** [comment]
Thanks @JHlozek !

I'll close this issue so we center the discussion only in #3
