### ISSUE TITLE
Hidden prints improvement

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/olinda#13]
A small issue, upon calling olinda a whole warning notices appear (I think related to ZairaChem), could these be hidden for better user experience? I see there is a class of HiddenPrints, maye this can help?
Also probably once olinda does not require zairachem it will not show on start at least I guess

**Comment by JHlozek** [comment]
I've worked on this class a bit more to reduce the outputs from ZairaChem and tensorflow. There's still some cuda related warnings that I don't know how to prevent (same as within ZairaChem), but the majority of messages are covered by HiddenPrints.

**Comment by GemmaTuron** [comment]
great yeah, we will work on the annoying cuda messages from ZairaChem's end which will also delete them from here I hope!
