### ISSUE TITLE
Benchmarking Olinda with TDC

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/olinda#7]
Once the best parameters for ZairaChem Model distillation have been identified (see [issue 46](https://github.com/ersilia-os/zaira-chem/issues/46)) we need to benchmark Olinda's models performance.
We can use the ADMET classification datasets available in TDC and replicate the work done in https://github.com/ersilia-os/zaira-chem-tdc

1. Use the data prepared in the `/data` folder. Each dataset has a train and test split. 
2. Train a ZairaChem model, and distill it
3. Compare predictions on the test dataset with the ZairaChem and the Olinda model

Do we want to do a 5-fold cross-validation? In that case, the same pipeline but repeating the pipeline x5 and saving each model as fold1, fold2 ...(TDC separates train/validation/test, and what we provide as train is the train+validation) ZairaChem makes its own train/validation splits inside the pipeline.

**Comment by JHlozek** [comment]
The Olinda benchmarking has now begun on the data in https://github.com/ersilia-os/zaira-chem-tdc

I'll also be measure the prospective performance for Olinda on H3D data compared to the respective ZairaChem models.

**Comment by JHlozek** [comment]
Hi @miquelduranfrigola and @GemmaTuron 

Here are the benchmarking results for ZairaChem, Olinda, and Olinda training directly on the experimental data:

| assay                          |   zaira-chem auroc |   zaira-chem stdev |   olinda auroc |   olinda stdev |   delta |   perc_performance |   olinda direct auroc |   olinda direct stdev |
|:-------------------------------|-------------------:|-------------------:|---------------:|---------------:|--------:|-------------------:|----------------------:|----------------------:|
| Bioavailability_Ma             |              0.693 |              0.009 |          0.676 |          0.022 |  -0.017 |               0.98 |                 0.617 |                 0.053 |
| HIA_Hou                        |              0.99  |              0.004 |          0.888 |          0.194 |  -0.102 |               0.9  |                 0.859 |                 0.045 |
| Pgp_Broccatelli                |              0.941 |              0.005 |          0.936 |          0.006 |  -0.005 |               0.99 |                 0.924 |                 0.005 |
| BBB_Martins                    |              0.921 |              0.007 |          0.899 |          0.009 |  -0.022 |               0.98 |                 0.786 |                 0.018 |
| CYP2C9_Veith                   |              0.779 |              0.005 |          0.744 |          0.006 |  -0.035 |               0.96 |                 0.717 |                 0.01  |
| CYP2D6_Veith                   |              0.707 |              0.01  |          0.652 |          0.012 |  -0.055 |               0.92 |                 0.609 |                 0.026 |
| CYP3A4_Veith                   |              0.858 |              0.007 |          0.846 |          0.003 |  -0.012 |               0.99 |                 0.823 |                 0.01  |
| CYP2C9_Substrate_CarbonMangels |              0.42  |              0.011 |          0.415 |          0.019 |  -0.005 |               0.99 |                 0.387 |                 0.021 |
| CYP2D6_Substrate_CarbonMangels |              0.719 |              0.023 |          0.693 |          0.022 |  -0.026 |               0.96 |                 0.654 |                 0.059 |
| CYP3A4_Substrate_CarbonMangels |              0.633 |              0.01  |          0.615 |          0.01  |  -0.018 |               0.97 |                 0.586 |                 0.028 |
| hERG                           |              0.861 |              0.005 |          0.843 |          0.021 |  -0.018 |               0.98 |                 0.767 |                 0.033 |
| AMES                           |              0.853 |              0.005 |          0.823 |          0.005 |  -0.03  |               0.96 |                 0.788 |                 0.011 |
| DILI                           |              0.933 |              0.012 |          0.914 |          0.023 |  -0.019 |               0.98 |                 0.807 |                 0.026 |

My repo has all the code and Olinda models as well as the H3D model performance comparison (https://github.com/JHlozek/olinda-tdc). We can transfer this to Ersilia's github account at some point.

**Comment by miquelduranfrigola** [comment]
Thanks @JHlozek 
These results are excellent. Olinda on precalculated data does not dramatically lose performance, and Olinda on training data directly is not as good (10% loss or even more?).
Quick question: are Bioavailability_Ma, CYP2C9_Substrate_CarbonMangels and CYP3A4_Substrate_CarbonMangels expected to be low, according to the TDC leaderboard?

**Comment by GemmaTuron** [comment]
awesome thanks @JHlozek !

@miquelduranfrigola :
- Bioavailability is lower (max values 0.78 AUROC). We are still scoring 6th in the leaderboard with 0.706 ± 0.031
- CYP2C9 Substrate are measured with AUPRC so I cannot do the direct comparison, I recall though they where more difficult tasks. ZairaChem is still scoring first.
- CYP3A$ substrate has low AUROCs (0.667 the winning). Zairachem scores nineth

**Comment by JHlozek** [comment]
@miquelduranfrigola and @GemmaTuron

Quick update, the metrics above are all calculated with the ```group.evaluate_many()``` of tdc so the CYP2C9 number will actually be a AUPRC score. I've updated the column titles to remove the confusion.

**Comment by GemmaTuron** [comment]
oh perfect then we are actually in the same range of 0.4 for AUPRC in CYP2C9 Substrate.
I think we can close this issue then? If you transfer the repository @JHlozek I will use the data there to create the first paper figure when we get there :)

**Comment by JHlozek** [comment]
@GemmaTuron, I've transferred the benchmarking repo to ersilia. It also contains predictions for H3D - I've just scrubbed the files to remove the SMILES strings though.

So I think this issue can be closed. :)
